### ISSUE TITLE
Live Trading

### ISSUE THREAD

**Issue by Tezeug** [ranjotsingh/DigitalTrader#1]
Hello.
I have turned on (+ history too) the live trading, it has logged some trades but nothing on Binance.
What to do?

**Comment by Tezeug** [comment]
API Key/Secret not set in bot.py error

Although it should be okay.

**Comment by ranjotsingh** [comment]
Use your API key and secret from Binance and set ACTIVE in bot.py (line 10) to True.

**Comment by Tezeug** [comment]
I’ve done that.

**Comment by Tezeug** [comment]
`if API_KEY == "" or SECRET + "":
	print("Warning: API Key/Secret not set in", FILENAME)
	ACTIVE = False`

Should not there be `SECRET == ""`?

**Comment by Tezeug** [comment]
Now, it works.
But I just got this error when the bot was selling the coins.

`Selling: Completed at price ...
ERROR:root:Filter failure: PRICE_FILTER
Buying: Completed at price ...`

**Comment by Tezeug** [comment]
It logs Buying, Selling completed but nothing shows in the order history. It just made a few, I would say quite random trades.
